services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Eventify@DB2026!
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  database-setup:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - database
    command: >
      bash -c '
      sleep 15;
      /opt/mssql-tools/bin/sqlcmd -S database -U sa -P "Eventify@DB2026!" -Q "IF DB_ID('\''event_management'\'') IS NULL CREATE DATABASE event_management;"
      '

  server:
    build:
      context: ./server
    ports:
      - "8000:8000"
    depends_on:
      - database
      - database-setup
    volumes:
      - ./server:/app
      - server_vendor:/app/vendor
    environment:
      DB_CONNECTION: sqlsrv
      DB_HOST: database
      DB_PORT: 1433
      DB_DATABASE: event_management
      DB_USERNAME: sa
      DB_PASSWORD: Eventify@DB2026!
      APP_URL: http://localhost:8000
      FRONTEND_URL: http://localhost:5173

  client:
    build:
      context: ./client
    ports:
      - "3000:5173"
    stdin_open: true
    tty: true
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true

volumes:
  mssql_data:
  server_vendor: